object FormNightModeRGBQuickEdit4K: TFormNightModeRGBQuickEdit4K
  Left = 1233
  Top = 622
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'RGB Quick Edit (4K)'
  ClientHeight = 551
  ClientWidth = 1061
  Color = clTeal
  DefaultMonitor = dmMainForm
  Font.Charset = ANSI_CHARSET
  Font.Color = clBlack
  Font.Height = -21
  Font.Name = 'Segoe UI'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesktopCenter
  Scaled = False
  PixelsPerInch = 96
  TextHeight = 30
  object NightModeRGBQuickEdit_RedLabel: TShadowLabel
    Left = 16
    Top = 127
    Width = 38
    Height = 31
    Caption = 'Red'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -21
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeRGBQuickEdit_GreenLabel: TShadowLabel
    Left = 16
    Top = 223
    Width = 58
    Height = 31
    Caption = 'Green'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -21
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeRGBQuickEdit_BlueLabel: TShadowLabel
    Left = 16
    Top = 319
    Width = 43
    Height = 31
    Caption = 'Blue'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -21
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeColorBoxExHint: TShadowLabel
    Left = 16
    Top = 12
    Width = 1029
    Height = 65
    Alignment = taCenter
    AutoSize = False
    Caption = 'ColorBoxEx Hint Text'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = clCream
    Font.Height = -21
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeRGBQuickEdit_HexLabel2: TShadowLabel
    Left = 16
    Top = 415
    Width = 39
    Height = 31
    Caption = 'Hex'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -21
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeRGBQuickEdit_ColorSampleLabel: TShadowLabel
    Left = 813
    Top = 90
    Width = 198
    Height = 31
    Caption = 'New              Current'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -21
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeRGBQuickEdit_ColorSample_CurrentLabel: TShadowLabel
    Left = 912
    Top = 353
    Width = 126
    Height = 31
    Alignment = taCenter
    AutoSize = False
    Caption = '255, 255, 255'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -21
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeRGBQuickEdit_HexLabel: TShadowLabel
    Left = 80
    Top = 415
    Width = 75
    Height = 31
    AutoSize = False
    Caption = '000000'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -21
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeKeysHintLabel: TShadowLabel
    Left = 16
    Top = 485
    Width = 460
    Height = 55
    Caption = 
      'TAB : Change Focus   ENTER : Apply   ESC : Abort Mouse Left-Clic' +
      'k on Current Color To Reset'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = clSilver
    Font.Height = -21
    Font.Name = 'Trebuchet MS'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
    WordWrap = True
  end
  object TrackBarColorB_Label: TShadowLabel
    Left = 121
    Top = 361
    Width = 543
    Height = 25
    Caption = '000       064        128        192       255'
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -21
    Font.Name = 'Consolas'
    Font.Style = []
    ParentFont = False
    ShadowColor = clGray
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object TrackBarColorR_Label: TShadowLabel
    Left = 121
    Top = 169
    Width = 543
    Height = 25
    Caption = '000       064        128        192       255'
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -21
    Font.Name = 'Consolas'
    Font.Style = []
    ParentFont = False
    ShadowColor = clGray
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object TrackBarColorG_Label: TShadowLabel
    Left = 121
    Top = 265
    Width = 543
    Height = 25
    Caption = '000       064        128        192       255'
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -21
    Font.Name = 'Consolas'
    Font.Style = []
    ParentFont = False
    ShadowColor = clGray
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object TrackBarColorR_ButtonDec: TBitBtnEx
    Tag = -1
    Left = 80
    Top = 124
    Width = 37
    Height = 37
    Caption = #231
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clBlack
    Font.Height = -21
    Font.Name = 'Wingdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 5
  end
  object TrackBarColorR_ButtonInc: TBitBtnEx
    Tag = 1
    Left = 667
    Top = 124
    Width = 37
    Height = 37
    Caption = #232
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clBlack
    Font.Height = -21
    Font.Name = 'Wingdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 6
  end
  object TrackBarColorG_ButtonDec: TBitBtnEx
    Tag = -1
    Left = 80
    Top = 220
    Width = 37
    Height = 37
    Caption = #231
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clBlack
    Font.Height = -21
    Font.Name = 'Wingdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 7
  end
  object TrackBarColorG_ButtonInc: TBitBtnEx
    Tag = 1
    Left = 667
    Top = 220
    Width = 37
    Height = 37
    Caption = #232
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clBlack
    Font.Height = -21
    Font.Name = 'Wingdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 8
  end
  object TrackBarColorB_ButtonDec: TBitBtnEx
    Tag = -1
    Left = 80
    Top = 316
    Width = 37
    Height = 37
    Caption = #231
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clBlack
    Font.Height = -21
    Font.Name = 'Wingdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 9
  end
  object TrackBarColorB_ButtonInc: TBitBtnEx
    Tag = 1
    Left = 667
    Top = 316
    Width = 37
    Height = 37
    Caption = #232
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clBlack
    Font.Height = -21
    Font.Name = 'Wingdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 10
  end
  object NightModeRGBQuickEdit_Red: TEditEx
    Left = 714
    Top = 124
    Width = 41
    Height = 36
    AutoSize = False
    Ctl3D = True
    ParentCtl3D = False
    TabOrder = 0
    Text = '254'
    UseCustomBorder = True
  end
  object NightModeRGBQuickEdit_Green: TEditEx
    Left = 714
    Top = 220
    Width = 41
    Height = 36
    AutoSize = False
    Ctl3D = True
    ParentCtl3D = False
    TabOrder = 1
    Text = '444'
    UseCustomBorder = True
  end
  object NightModeRGBQuickEdit_Blue: TEditEx
    Left = 714
    Top = 316
    Width = 41
    Height = 36
    AutoSize = False
    Ctl3D = True
    ParentCtl3D = False
    TabOrder = 2
    Text = '000'
    UseCustomBorder = True
  end
  object NightModeRGBQuickEdit_ButtonApply: TBitBtnEx
    Left = 693
    Top = 490
    Width = 168
    Height = 45
    Hint = 'Set current color to colorbox'
    Caption = 'Apply'
    ModalResult = 1
    ParentShowHint = False
    ShowHint = True
    TabOrder = 3
  end
  object NightModeRGBQuickEdit_ButtonAbort: TBitBtnEx
    Left = 877
    Top = 490
    Width = 168
    Height = 45
    Caption = 'Abort'
    ModalResult = 2
    TabOrder = 4
  end
  object TrackBarColorR: TXiTrackBar
    Tag = -1
    Left = 121
    Top = 120
    Width = 542
    Height = 45
    BackColor = 2565927
    TickColor = 12574688
    DisabledTickColor = clGray
    SlideBorderColor = 1315860
    SlideFaceColor = 3289650
    SlideGradColor = 5263440
    DisabledSlideBorderColor = 2368548
    DisabledSlideFaceColor = 2565927
    DisabledSlideGradColor = 3289650
    DisabledThumbBorderColor = 2368548
    DisabledThumbFaceColor = 3289650
    DisabledThumbGradColor = 4342338
    ThumbBorderColor = 1315860
    ThumbFaceColor = clGray
    ThumbGradColor = 5000268
    OverThumbBorderColor = 1315860
    OverThumbFaceColor = clMedGray
    OverThumbGradColor = 9803157
    DownThumbBorderColor = 1315860
    DownThumbFaceColor = 6316128
    DownThumbGradColor = 3750201
    SmoothCorners = True
    ColorScheme = csDark
    Max = 255
    Frequency = 16
    TickStyle = tsAuto
    TickMarks = tmBottomRight
    Orientation = trHorizontal
  end
  object TrackBarColorG: TXiTrackBar
    Tag = -1
    Left = 121
    Top = 216
    Width = 542
    Height = 45
    BackColor = 2565927
    TickColor = 12574688
    DisabledTickColor = clGray
    SlideBorderColor = 1315860
    SlideFaceColor = 3289650
    SlideGradColor = 5263440
    DisabledSlideBorderColor = 2368548
    DisabledSlideFaceColor = 2565927
    DisabledSlideGradColor = 3289650
    DisabledThumbBorderColor = 2368548
    DisabledThumbFaceColor = 3289650
    DisabledThumbGradColor = 4342338
    ThumbBorderColor = 1315860
    ThumbFaceColor = clGray
    ThumbGradColor = 5000268
    OverThumbBorderColor = 1315860
    OverThumbFaceColor = clMedGray
    OverThumbGradColor = 9803157
    DownThumbBorderColor = 1315860
    DownThumbFaceColor = 6316128
    DownThumbGradColor = 3750201
    SmoothCorners = True
    ColorScheme = csDark
    Max = 255
    Position = 128
    Frequency = 16
    TickStyle = tsAuto
    TickMarks = tmBottomRight
    Orientation = trHorizontal
  end
  object TrackBarColorB: TXiTrackBar
    Tag = -1
    Left = 121
    Top = 312
    Width = 542
    Height = 45
    BackColor = 2565927
    TickColor = 12574688
    DisabledTickColor = clGray
    SlideBorderColor = 1315860
    SlideFaceColor = 3289650
    SlideGradColor = 5263440
    DisabledSlideBorderColor = 2368548
    DisabledSlideFaceColor = 2565927
    DisabledSlideGradColor = 3289650
    DisabledThumbBorderColor = 2368548
    DisabledThumbFaceColor = 3289650
    DisabledThumbGradColor = 4342338
    ThumbBorderColor = 1315860
    ThumbFaceColor = clGray
    ThumbGradColor = 5000268
    OverThumbBorderColor = 1315860
    OverThumbFaceColor = clMedGray
    OverThumbGradColor = 9803157
    DownThumbBorderColor = 1315860
    DownThumbFaceColor = 6316128
    DownThumbGradColor = 3750201
    SmoothCorners = True
    ColorScheme = csDark
    Max = 255
    Position = 255
    Frequency = 16
    TickStyle = tsAuto
    TickMarks = tmBottomRight
    Orientation = trHorizontal
  end
  object NightModeRGBQuickEdit_ColorSample: TPanelEx
    Left = 765
    Top = 124
    Width = 140
    Height = 228
    Color1 = clWhite
    Color2 = clSilver
    Color3 = clYellow
    Color4 = clTeal
    ColorFrame = clGray
    ColorInnerFrame = clGreen
    Frames = [frLeft, frTop, frBottom]
    ParentBackground = False
    Style = vgSolid
  end
  object NightModeRGBQuickEdit_ColorSample_Current: TPanelEx
    Left = 905
    Top = 124
    Width = 140
    Height = 228
    Hint = 'Click to restore color'
    Color1 = clBlue
    Color2 = clSilver
    Color3 = clYellow
    Color4 = clTeal
    ColorFrame = clGray
    ColorInnerFrame = clGreen
    Frames = [frTop, frRight, frBottom]
    ParentBackground = False
    ShowHint = True
    Style = vgSolid
  end
  object LockSliders: TAdvOfficeCheckBoxEx
    Left = 524
    Top = 413
    Width = 140
    Height = 36
    Hint = 'One slider to move them all!'
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -21
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentFont = False
    ShowHint = True
    TabOrder = 16
    Alignment = taRightJustify
    ButtonVertAlign = tlCenter
    Caption = 'Lock Sliders'
    ReturnIsTab = False
    Themed = True
    CustomIconsEnabled = False
    CustomEnableIconHD = True
  end
end
