object FormAbout: TFormAbout
  Left = 1356
  Top = 886
  BorderIcons = [biSystemMenu]
  BorderStyle = bsNone
  Caption = 'About...'
  ClientHeight = 450
  ClientWidth = 640
  Color = clBtnFace
  DefaultMonitor = dmMainForm
  Font.Charset = ANSI_CHARSET
  Font.Color = clBlack
  Font.Height = -13
  Font.Name = 'Segoe UI'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  Scaled = False
  OnCreate = FormCreate
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 17
  object ImageAbout: TImage32
    Left = 0
    Top = 0
    Width = 640
    Height = 450
    Align = alClient
    Bitmap.DrawMode = dmBlend
    Bitmap.ResamplerClassName = 'TNearestResampler'
    BitmapAlign = baTopLeft
    Color = clBlack
    ParentColor = False
    Scale = 1.000000000000000000
    ScaleMode = smNormal
    TabOrder = 0
    OnClick = ImageAboutClick
  end
end
