object FormAbout: TFormAbout
  Left = 705
  Top = 316
  BorderIcons = [biSystemMenu]
  BorderStyle = bsNone
  Caption = 'About...'
  ClientHeight = 450
  ClientWidth = 640
  Color = clBtnFace
  DefaultMonitor = dmMainForm
  Font.Charset = ANSI_CHARSET
  Font.Color = clBlack
  Font.Height = -13
  Font.Name = 'Segoe UI'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Position = poScreenCenter
  Scaled = False
  OnCreate = FormCreate
  OnKeyPress = FormKeyPress
  PixelsPerInch = 96
  TextHeight = 17
  object ImageAbout: TImage32
    Left = 0
    Top = 0
    Width = 640
    Height = 450
    Align = alClient
    Bitmap.DrawMode = dmBlend
    Bitmap.ResamplerClassName = 'TNearestResampler'
    BitmapAlign = baTopLeft
    Color = clBlack
    ParentColor = False
    Scale = 1.000000000000000000
    ScaleMode = smNormal
    TabOrder = 0
    OnClick = ImageAboutClick
    object LabelVersion: TShadowLabel
      Left = 573
      Top = 227
      Width = 44
      Height = 14
      Alignment = taRightJustify
      Caption = 'v12.0.0'
      Font.Charset = ANSI_CHARSET
      Font.Color = clOlive
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
      ShadowColor = clNavy
      ShadowEnabled = True
      EllipsType = etNone
      Transparent = True
    end
  end
end
