object FormApplyFilterMsgBox: TFormApplyFilterMsgBox
  Left = 849
  Top = 422
  BorderIcons = []
  BorderStyle = bsNone
  ClientHeight = 82
  ClientWidth = 514
  Color = 15856113
  DefaultMonitor = dmMainForm
  Font.Charset = ANSI_CHARSET
  Font.Color = clBlack
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  Scaled = False
  PixelsPerInch = 96
  TextHeight = 15
  object PanelBackground: TPanelEx
    Left = 0
    Top = 0
    Width = 514
    Height = 82
    Align = alClient
    Color1 = clWhite
    Color2 = clGray
    Color3 = 7891291
    Color4 = 16112579
    ColorFrame = clSilver
    ColorInnerFrame = 7891291
    EnableInnerFrame = True
    EnableCustomBorder = ecbDouble
    Frames = []
    ParentBackground = False
    Style = vgSimple
    OnMouseDown = PanelBackgroundMouseDown
    object LabelBoxMessageTitle: TShadowLabel
      Left = 46
      Top = 19
      Width = 452
      Height = 17
      AutoSize = False
      Caption = 'Games Filters'
      Font.Charset = ANSI_CHARSET
      Font.Color = clBlack
      Font.Height = -13
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clMaroon
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelBoxMessage: TShadowLabel
      Left = 46
      Top = 44
      Width = 452
      Height = 17
      AutoSize = False
      Caption = 'Applying filters, please wait...'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = 89
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object MsgIcon: TImage
      Left = 16
      Top = 16
      Width = 24
      Height = 24
      Transparent = True
    end
  end
end
