object FormCleanInstallGuide: TFormCleanInstallGuide
  Left = 1069
  Top = 625
  BorderIcons = [biSystemMenu]
  BorderStyle = bsNone
  Caption = 'Setup Guide'
  ClientHeight = 392
  ClientWidth = 636
  Color = 15856113
  DefaultMonitor = dmMainForm
  Font.Charset = ANSI_CHARSET
  Font.Color = clBlack
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  Scaled = False
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 15
  object ImageCleanInstall: TImage32
    Left = 0
    Top = 0
    Width = 636
    Height = 392
    Bitmap.DrawMode = dmBlend
    Bitmap.ResamplerClassName = 'TNearestResampler'
    BitmapAlign = baTopLeft
    Color = 3289650
    ParentColor = False
    Scale = 1.000000000000000000
    ScaleMode = smNormal
    TabOrder = 0
    OnMouseDown = ImageCleanInstallMouseDown
    object LabelOption_SelectArcadeEmulators_FileStatus: TShadowLabel
      Left = 351
      Top = 154
      Width = 137
      Height = 13
      Hint = '[config file'
      Caption = 'config file found'
      Font.Charset = OEM_CHARSET
      Font.Color = clLime
      Font.Height = -12
      Font.Name = 'Terminal'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clGreen
      ShadowEnabled = True
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelOption_SelectConsoleComputerGamesFolders_FileStatus: TShadowLabel
      Left = 346
      Top = 241
      Width = 201
      Height = 13
      Hint = '[folders config file'
      Caption = 'folders config file found'
      Font.Charset = OEM_CHARSET
      Font.Color = clLime
      Font.Height = -12
      Font.Name = 'Terminal'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clGreen
      ShadowEnabled = True
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelQuickSetupGuide: TShadowLabel
      Left = 153
      Top = 309
      Width = 330
      Height = 16
      Alignment = taCenter
      AutoSize = False
      Caption = 'Click here to view the quick setup guide'
      Font.Charset = OEM_CHARSET
      Font.Color = 12779458
      Font.Height = -12
      Font.Name = 'Terminal'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = 15616
      ShadowEnabled = True
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
      OnClick = LabelQuickSetupGuideClick
      OnMouseEnter = LabelQuickSetupGuideMouseEnter
      OnMouseLeave = LabelQuickSetupGuideMouseLeave
    end
    object Option_SelectArcadeEmulators: TAdvOfficeCheckBoxEx
      Left = 10
      Top = 150
      Width = 335
      Height = 20
      Checked = True
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      Alignment = taLeftJustify
      ReturnIsTab = False
      ShadowEnabled = True
      State = cbChecked
      Themed = True
      CustomIconsEnabled = False
      CustomEnableIconHD = False
      CustomIconsImages = FormMain.IL_CheckBoxRadioButtonIcons
      CustomIconsImagesHD = FormMain.IL_CheckBoxRadioButtonIconsHD
    end
    object Option_CreateArcadeGamesList: TAdvOfficeCheckBoxEx
      Left = 10
      Top = 179
      Width = 271
      Height = 20
      Checked = True
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 1
      Alignment = taLeftJustify
      ReturnIsTab = False
      ShadowEnabled = True
      State = cbChecked
      Themed = True
      CustomIconsEnabled = False
      CustomEnableIconHD = False
      CustomIconsImages = FormMain.IL_CheckBoxRadioButtonIcons
      CustomIconsImagesHD = FormMain.IL_CheckBoxRadioButtonIconsHD
    end
    object Option_SelectConsoleComputerEmulators: TAdvOfficeCheckBoxEx
      Left = 10
      Top = 208
      Width = 599
      Height = 20
      Checked = True
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 2
      Alignment = taLeftJustify
      ReturnIsTab = False
      ShadowEnabled = True
      State = cbChecked
      Themed = True
      CustomIconsEnabled = False
      CustomEnableIconHD = False
      CustomIconsImages = FormMain.IL_CheckBoxRadioButtonIcons
      CustomIconsImagesHD = FormMain.IL_CheckBoxRadioButtonIconsHD
    end
    object Option_SelectConsoleComputerGamesFolders: TAdvOfficeCheckBoxEx
      Left = 10
      Top = 237
      Width = 327
      Height = 20
      Checked = True
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 3
      Alignment = taLeftJustify
      ReturnIsTab = False
      ShadowEnabled = True
      State = cbChecked
      Themed = True
      CustomIconsEnabled = False
      CustomEnableIconHD = False
      CustomIconsImages = FormMain.IL_CheckBoxRadioButtonIcons
      CustomIconsImagesHD = FormMain.IL_CheckBoxRadioButtonIconsHD
    end
    object Option_CreateConsoleComputerGamesList: TAdvOfficeCheckBoxEx
      Left = 10
      Top = 266
      Width = 311
      Height = 20
      Checked = True
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Verdana'
      Font.Style = []
      ParentFont = False
      TabOrder = 4
      Alignment = taLeftJustify
      ReturnIsTab = False
      ShadowEnabled = True
      State = cbChecked
      Themed = True
      CustomIconsEnabled = False
      CustomEnableIconHD = False
      CustomIconsImages = FormMain.IL_CheckBoxRadioButtonIcons
      CustomIconsImagesHD = FormMain.IL_CheckBoxRadioButtonIconsHD
    end
    object NightMode: TAdvOfficeCheckBoxEx
      Left = 8
      Top = 345
      Width = 169
      Height = 20
      Hint = 'Check to use a dark theme'
      Checked = True
      Font.Charset = ANSI_CHARSET
      Font.Color = 12574688
      Font.Height = -12
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowHint = True
      TabOrder = 5
      OnClick = NightModeClick
      Alignment = taLeftJustify
      ReturnIsTab = False
      ShadowEnabled = True
      ShadowColor = 4213580
      State = cbChecked
      Themed = True
      CustomIconsEnabled = False
      CustomEnableIconHD = False
      CustomIconsImages = FormMain.IL_CheckBoxRadioButtonIcons
      CustomIconsImagesHD = FormMain.IL_CheckBoxRadioButtonIconsHD
    end
    object UseAlternateFrontendIcons: TAdvOfficeCheckBoxEx
      Left = 8
      Top = 365
      Width = 257
      Height = 20
      Hint = 'Use frontend icons from the "alternate" folders'
      Font.Charset = ANSI_CHARSET
      Font.Color = 12574688
      Font.Height = -12
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowHint = True
      TabOrder = 6
      Alignment = taLeftJustify
      ReturnIsTab = False
      ShadowEnabled = True
      ShadowColor = 4213580
      Themed = True
      CustomIconsEnabled = False
      CustomEnableIconHD = False
      CustomIconsImages = FormMain.IL_CheckBoxRadioButtonIcons
      CustomIconsImagesHD = FormMain.IL_CheckBoxRadioButtonIconsHD
    end
    object ButtonSkip: TBitBtnEx
      Left = 339
      Top = 359
      Width = 89
      Height = 25
      Caption = 'Skip'
      ModalResult = 5
      ParentShowHint = False
      ShowHint = True
      TabOrder = 9
    end
    object ButtonOk: TBitBtnEx
      Left = 439
      Top = 359
      Width = 89
      Height = 25
      Caption = 'Continue'
      ModalResult = 1
      ParentShowHint = False
      ShowHint = True
      TabOrder = 7
    end
    object ButtonCancel: TBitBtnEx
      Left = 539
      Top = 359
      Width = 89
      Height = 25
      Hint = 'Terminate the application'
      Caption = 'Quit'
      ModalResult = 2
      ParentShowHint = False
      ShowHint = True
      TabOrder = 8
      OnClick = ButtonCancelClick
    end
    object UltraHD_4KModeDisable: TAdvOfficeCheckBoxEx
      Left = 8
      Top = 324
      Width = 169
      Height = 20
      Hint = 
        'Frontend elements scale to a 4K resolution (check to disable tha' +
        't)'
      Font.Charset = ANSI_CHARSET
      Font.Color = 12574688
      Font.Height = -12
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowHint = True
      TabOrder = 10
      Visible = False
      OnClick = UltraHD_4KModeDisableClick
      Alignment = taLeftJustify
      ReturnIsTab = False
      ShadowEnabled = True
      ShadowColor = 4213580
      Themed = True
      CustomIconsEnabled = False
      CustomEnableIconHD = False
      CustomIconsImages = FormMain.IL_CheckBoxRadioButtonIcons
      CustomIconsImagesHD = FormMain.IL_CheckBoxRadioButtonIconsHD
    end
  end
end
