object FormImageLayoutDimensions: TFormImageLayoutDimensions
  Left = 725
  Top = 336
  BorderIcons = [biSystemMenu]
  BorderStyle = bsToolWindow
  Caption = 'Layout Dimensions'
  ClientHeight = 327
  ClientWidth = 273
  Color = 1117964
  DefaultMonitor = dmMainForm
  Font.Charset = ANSI_CHARSET
  Font.Color = clBlack
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Scaled = False
  OnCloseQuery = FormCloseQuery
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 15
  object LabelImage4: TShadowLabel
    Left = 54
    Top = 296
    Width = 164
    Height = 18
    Hint = 'Image 4:'
    Caption = 'Image 4:                    pixels'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = clGray
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object LabelImage3: TShadowLabel
    Left = 54
    Top = 276
    Width = 164
    Height = 18
    Hint = 'Image 3:'
    Caption = 'Image 3:                    pixels'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = clGray
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object LabelImage2: TShadowLabel
    Left = 54
    Top = 256
    Width = 164
    Height = 18
    Hint = 'Image 2:'
    Caption = 'Image 2:                    pixels'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = clGray
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object LabelImage1: TShadowLabel
    Left = 54
    Top = 236
    Width = 164
    Height = 18
    Hint = 'Image 1:'
    Caption = 'Image 1:                    pixels'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = clGray
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object LabelLayoutTitle: TShadowLabel
    Tag = -1
    Left = 8
    Top = 175
    Width = 257
    Height = 23
    Alignment = taCenter
    AutoSize = False
    Caption = 'Layout Title'
    Font.Charset = ANSI_CHARSET
    Font.Color = clRed
    Font.Height = -13
    Font.Name = 'Trebuchet MS'
    Font.Style = [fsBold]
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = clMaroon
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object LabelImagesPanel: TShadowLabel
    Left = 38
    Top = 208
    Width = 81
    Height = 18
    Caption = 'Images Panel:'
    Font.Charset = ANSI_CHARSET
    Font.Color = clYellow
    Font.Height = -13
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = clMaroon
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object LabelImagesPanelDimensions: TShadowLabel
    Left = 122
    Top = 208
    Width = 113
    Height = 21
    Alignment = taCenter
    AutoSize = False
    Caption = '1000x1000 pixels'
    Font.Charset = ANSI_CHARSET
    Font.Color = clYellow
    Font.Height = -13
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = clMaroon
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object LabelImage1Dimensions: TShadowLabel
    Left = 112
    Top = 236
    Width = 63
    Height = 18
    Alignment = taRightJustify
    AutoSize = False
    Caption = '1000x1000'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = clGray
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object LabelImage2Dimensions: TShadowLabel
    Left = 112
    Top = 256
    Width = 63
    Height = 18
    Alignment = taRightJustify
    AutoSize = False
    Caption = '1000x1000'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = clGray
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object LabelImage3Dimensions: TShadowLabel
    Left = 112
    Top = 276
    Width = 63
    Height = 18
    Alignment = taRightJustify
    AutoSize = False
    Caption = '1000x1000'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = clGray
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object LabelImage4Dimensions: TShadowLabel
    Left = 112
    Top = 296
    Width = 63
    Height = 18
    Alignment = taRightJustify
    AutoSize = False
    Caption = '1000x1000'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWhite
    Font.Height = -13
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = clGray
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = clBlack
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object ImageScrLayout: TImage32
    Left = 4
    Top = 4
    Width = 265
    Height = 165
    Bitmap.DrawMode = dmBlend
    Bitmap.ResamplerClassName = 'TNearestResampler'
    BitmapAlign = baTopLeft
    Scale = 1.000000000000000000
    ScaleMode = smNormal
    TabOrder = 0
  end
end
