object FormImageLayoutDimensions: TFormImageLayoutDimensions
  Left = 725
  Top = 336
  Width = 335
  Height = 414
  BorderIcons = [biSystemMenu]
  Caption = 'Layout Dimensions'
  Color = 1117964
  DefaultMonitor = dmMainForm
  Font.Charset = ANSI_CHARSET
  Font.Color = clBlack
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  KeyPreview = True
  OldCreateOrder = False
  Scaled = False
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 15
  object PanelImageLayoutDimensions: TPanelEx
    Left = 0
    Top = 0
    Width = 293
    Height = 351
    Color1 = 3289650
    Color2 = clSilver
    Color3 = clYellow
    Color4 = clTeal
    ColorFrame = 1
    ColorInnerFrame = 7891291
    EnableCustomBorder = ecbDouble
    Frames = []
    ParentBackground = False
    Style = vgSolid
    object PanelImageLayoutDimensLabel: TShadowLabel
      Left = 46
      Top = 8
      Width = 138
      Height = 16
      Caption = 'Image Layout Dimensions'
      Color = 5787720
      Font.Charset = ANSI_CHARSET
      Font.Color = clCream
      Font.Height = -12
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentColor = False
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = 5588805
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = 4210752
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object PanelImageLayoutDimensButtonClose: TShadowLabel
      Left = 12
      Top = 8
      Width = 28
      Height = 16
      Hint = 'Close'
      Alignment = taCenter
      AutoSize = False
      Caption = 'X'
      Color = 89
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentColor = False
      ParentFont = False
      ParentShowHint = False
      ShowAccelChar = False
      ShowHint = True
      ShadowColor = clBlack
      ShadowEnabled = True
      EllipsType = etNone
      ColorFrame = 23170
      ColorInnerFrame = clBlack
      EnableInnerFrame = True
      Frames = [lfrLeft, lfrTop, lfrRight, lfrBottom]
      Transparent = False
      Layout = tlCenter
      OnClick = PanelImageLayoutDimensButtonCloseClick
      OnMouseEnter = PanelImageLayoutDimensButtonCloseMouseEnter
      OnMouseLeave = PanelImageLayoutDimensButtonCloseMouseLeave
    end
    object LabelImage4: TShadowLabel
      Left = 62
      Top = 320
      Width = 164
      Height = 18
      Hint = 'Image 4:'
      Caption = 'Image 4:                    pixels'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clGray
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelImage3: TShadowLabel
      Left = 62
      Top = 300
      Width = 164
      Height = 18
      Hint = 'Image 3:'
      Caption = 'Image 3:                    pixels'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clGray
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelImage2: TShadowLabel
      Left = 62
      Top = 280
      Width = 164
      Height = 18
      Hint = 'Image 2:'
      Caption = 'Image 2:                    pixels'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clGray
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelImage1: TShadowLabel
      Left = 62
      Top = 260
      Width = 164
      Height = 18
      Hint = 'Image 1:'
      Caption = 'Image 1:                    pixels'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clGray
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelLayoutTitle: TShadowLabel
      Tag = -1
      Left = 16
      Top = 199
      Width = 257
      Height = 23
      Alignment = taCenter
      AutoSize = False
      Caption = 'Layout Title'
      Font.Charset = ANSI_CHARSET
      Font.Color = clRed
      Font.Height = -13
      Font.Name = 'Trebuchet MS'
      Font.Style = [fsBold]
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clMaroon
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelImagesPanel: TShadowLabel
      Left = 46
      Top = 232
      Width = 81
      Height = 18
      Caption = 'Images Panel:'
      Font.Charset = ANSI_CHARSET
      Font.Color = clYellow
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clMaroon
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelImagesPanelDimensions: TShadowLabel
      Left = 130
      Top = 232
      Width = 113
      Height = 21
      Alignment = taCenter
      AutoSize = False
      Caption = '1000x1000 pixels'
      Font.Charset = ANSI_CHARSET
      Font.Color = clYellow
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clMaroon
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelImage1Dimensions: TShadowLabel
      Left = 120
      Top = 260
      Width = 63
      Height = 18
      Alignment = taRightJustify
      AutoSize = False
      Caption = '1000x1000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clGray
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelImage2Dimensions: TShadowLabel
      Left = 120
      Top = 280
      Width = 63
      Height = 18
      Alignment = taRightJustify
      AutoSize = False
      Caption = '1000x1000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clGray
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelImage3Dimensions: TShadowLabel
      Left = 120
      Top = 300
      Width = 63
      Height = 18
      Alignment = taRightJustify
      AutoSize = False
      Caption = '1000x1000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clGray
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object LabelImage4Dimensions: TShadowLabel
      Left = 120
      Top = 320
      Width = 63
      Height = 18
      Alignment = taRightJustify
      AutoSize = False
      Caption = '1000x1000'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -13
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ShowAccelChar = False
      ShadowColor = clGray
      ShadowEnabled = False
      EllipsType = etNone
      ColorFrame = clBlack
      ColorInnerFrame = clBlack
      Frames = []
      Transparent = True
    end
    object ImageScrLayout: TImage32
      Left = 12
      Top = 28
      Width = 265
      Height = 165
      Bitmap.DrawMode = dmBlend
      Bitmap.ResamplerClassName = 'TNearestResampler'
      BitmapAlign = baTopLeft
      Scale = 1.000000000000000000
      ScaleMode = smNormal
      TabOrder = 0
    end
  end
end
