object FormNightModeRGBQuickEdit: TFormNightModeRGBQuickEdit
  Left = 1233
  Top = 622
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'RGB Quick Edit'
  ClientHeight = 262
  ClientWidth = 544
  Color = 2565927
  DefaultMonitor = dmMainForm
  Font.Charset = ANSI_CHARSET
  Font.Color = clBlack
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesktopCenter
  Scaled = False
  PixelsPerInch = 96
  TextHeight = 15
  object NightModeRGBQuickEdit_RedLabel: TShadowLabel
    Left = 16
    Top = 81
    Width = 21
    Height = 16
    Caption = 'Red'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -12
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeRGBQuickEdit_GreenLabel: TShadowLabel
    Left = 16
    Top = 112
    Width = 32
    Height = 16
    Caption = 'Green'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -12
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeRGBQuickEdit_BlueLabel: TShadowLabel
    Left = 16
    Top = 143
    Width = 24
    Height = 16
    Caption = 'Blue'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -12
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeKeysHintLabel: TShadowLabel
    Left = 16
    Top = 216
    Width = 259
    Height = 31
    Caption = 
      'TAB : Change Focus   ENTER : Apply   ESC : Abort Mouse Left-Clic' +
      'k on Current Color To Reset'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = clSilver
    Font.Height = -12
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
    WordWrap = True
  end
  object NightModeColorBoxExHint: TShadowLabel
    Left = 14
    Top = 12
    Width = 511
    Height = 31
    Alignment = taCenter
    AutoSize = False
    Caption = 'ColorBoxEx Hint Text'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = clCream
    Font.Height = -12
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeRGBQuickEdit_HexLabel2: TShadowLabel
    Left = 16
    Top = 174
    Width = 22
    Height = 16
    Caption = 'Hex'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -12
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeRGBQuickEdit_ColorSampleLabel: TShadowLabel
    Left = 377
    Top = 57
    Width = 125
    Height = 16
    Caption = 'New                    Current'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -12
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeRGBQuickEdit_ColorSample_CurrentLabel: TShadowLabel
    Left = 440
    Top = 167
    Width = 87
    Height = 16
    Alignment = taCenter
    AutoSize = False
    Caption = '255, 255, 255'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -12
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object NightModeRGBQuickEdit_HexLabel: TShadowLabel
    Left = 51
    Top = 174
    Width = 43
    Height = 16
    AutoSize = False
    Caption = '000000'
    Color = 5787720
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -12
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    ShowAccelChar = False
    ShadowColor = 5588805
    ShadowEnabled = False
    EllipsType = etNone
    ColorFrame = 4210752
    ColorInnerFrame = clBlack
    Frames = []
    Transparent = True
  end
  object TrackBarColorR_ButtonDec: TBitBtnEx
    Tag = -1
    Left = 51
    Top = 78
    Width = 22
    Height = 21
    Caption = #231
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Wingdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 5
    OnClick = TrackBarColorR_ButtonDecClick
  end
  object TrackBarColorR_ButtonInc: TBitBtnEx
    Tag = 1
    Left = 277
    Top = 78
    Width = 22
    Height = 21
    Caption = #232
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Wingdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 6
    OnClick = TrackBarColorR_ButtonDecClick
  end
  object TrackBarColorG_ButtonDec: TBitBtnEx
    Tag = -1
    Left = 51
    Top = 109
    Width = 22
    Height = 21
    Caption = #231
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Wingdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 7
    OnClick = TrackBarColorG_ButtonDecClick
  end
  object TrackBarColorG_ButtonInc: TBitBtnEx
    Tag = 1
    Left = 277
    Top = 109
    Width = 22
    Height = 21
    Caption = #232
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Wingdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 8
    OnClick = TrackBarColorG_ButtonDecClick
  end
  object TrackBarColorB_ButtonDec: TBitBtnEx
    Tag = -1
    Left = 51
    Top = 140
    Width = 22
    Height = 21
    Caption = #231
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Wingdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 9
    OnClick = TrackBarColorB_ButtonDecClick
  end
  object TrackBarColorB_ButtonInc: TBitBtnEx
    Tag = 1
    Left = 277
    Top = 140
    Width = 22
    Height = 21
    Caption = #232
    Font.Charset = SYMBOL_CHARSET
    Font.Color = clBlack
    Font.Height = -15
    Font.Name = 'Wingdings'
    Font.Style = []
    ParentFont = False
    TabOrder = 10
    OnClick = TrackBarColorB_ButtonDecClick
  end
  object NightModeRGBQuickEdit_Red: TEditEx
    Left = 306
    Top = 78
    Width = 29
    Height = 21
    AutoSize = False
    Ctl3D = True
    ParentCtl3D = False
    TabOrder = 0
    Text = '000'
    OnChange = NightModeRGBQuickEdit_RedChange
    OnKeyPress = NightModeRGBQuickEdit_RedKeyPress
    UseCustomBorder = True
  end
  object NightModeRGBQuickEdit_Green: TEditEx
    Left = 306
    Top = 109
    Width = 29
    Height = 21
    AutoSize = False
    Ctl3D = True
    ParentCtl3D = False
    TabOrder = 1
    Text = '000'
    OnChange = NightModeRGBQuickEdit_RedChange
    OnKeyPress = NightModeRGBQuickEdit_RedKeyPress
    UseCustomBorder = True
  end
  object NightModeRGBQuickEdit_Blue: TEditEx
    Left = 306
    Top = 140
    Width = 29
    Height = 21
    AutoSize = False
    Ctl3D = True
    ParentCtl3D = False
    TabOrder = 2
    Text = '000'
    OnChange = NightModeRGBQuickEdit_RedChange
    OnKeyPress = NightModeRGBQuickEdit_RedKeyPress
    UseCustomBorder = True
  end
  object NightModeRGBQuickEdit_ButtonApply: TBitBtnEx
    Left = 341
    Top = 222
    Width = 86
    Height = 25
    Hint = 'Set current color to colorbox'
    Caption = 'Apply'
    ModalResult = 1
    ParentShowHint = False
    ShowHint = True
    TabOrder = 3
  end
  object NightModeRGBQuickEdit_ButtonAbort: TBitBtnEx
    Left = 443
    Top = 222
    Width = 86
    Height = 25
    Caption = 'Abort'
    ModalResult = 2
    TabOrder = 4
  end
  object TrackBarColorR: TXiTrackBar
    Tag = -1
    Left = 75
    Top = 74
    Width = 200
    Height = 29
    BackColor = 2565927
    TickColor = 12574688
    DisabledTickColor = clGray
    SlideBorderColor = 1315860
    SlideFaceColor = 3289650
    SlideGradColor = 5263440
    DisabledSlideBorderColor = 2368548
    DisabledSlideFaceColor = 2565927
    DisabledSlideGradColor = 3289650
    DisabledThumbBorderColor = 2368548
    DisabledThumbFaceColor = 3289650
    DisabledThumbGradColor = 4342338
    ThumbBorderColor = 1315860
    ThumbFaceColor = clGray
    ThumbGradColor = 5000268
    OverThumbBorderColor = 1315860
    OverThumbFaceColor = clMedGray
    OverThumbGradColor = 9803157
    DownThumbBorderColor = 1315860
    DownThumbFaceColor = 6316128
    DownThumbGradColor = 3750201
    SmoothCorners = True
    ColorScheme = csDark
    Max = 255
    Frequency = 16
    TickStyle = tsAuto
    TickMarks = tmBottomRight
    Orientation = trHorizontal
    OnChange = TrackBarColorRChange
  end
  object TrackBarColorG: TXiTrackBar
    Tag = -1
    Left = 75
    Top = 105
    Width = 200
    Height = 29
    BackColor = 2565927
    TickColor = 12574688
    DisabledTickColor = clGray
    SlideBorderColor = 1315860
    SlideFaceColor = 3289650
    SlideGradColor = 5263440
    DisabledSlideBorderColor = 2368548
    DisabledSlideFaceColor = 2565927
    DisabledSlideGradColor = 3289650
    DisabledThumbBorderColor = 2368548
    DisabledThumbFaceColor = 3289650
    DisabledThumbGradColor = 4342338
    ThumbBorderColor = 1315860
    ThumbFaceColor = clGray
    ThumbGradColor = 5000268
    OverThumbBorderColor = 1315860
    OverThumbFaceColor = clMedGray
    OverThumbGradColor = 9803157
    DownThumbBorderColor = 1315860
    DownThumbFaceColor = 6316128
    DownThumbGradColor = 3750201
    SmoothCorners = True
    ColorScheme = csDark
    Max = 255
    Frequency = 16
    TickStyle = tsAuto
    TickMarks = tmBottomRight
    Orientation = trHorizontal
    OnChange = TrackBarColorGChange
  end
  object TrackBarColorB: TXiTrackBar
    Tag = -1
    Left = 75
    Top = 136
    Width = 200
    Height = 29
    BackColor = 2565927
    TickColor = 12574688
    DisabledTickColor = clGray
    SlideBorderColor = 1315860
    SlideFaceColor = 3289650
    SlideGradColor = 5263440
    DisabledSlideBorderColor = 2368548
    DisabledSlideFaceColor = 2565927
    DisabledSlideGradColor = 3289650
    DisabledThumbBorderColor = 2368548
    DisabledThumbFaceColor = 3289650
    DisabledThumbGradColor = 4342338
    ThumbBorderColor = 1315860
    ThumbFaceColor = clGray
    ThumbGradColor = 5000268
    OverThumbBorderColor = 1315860
    OverThumbFaceColor = clMedGray
    OverThumbGradColor = 9803157
    DownThumbBorderColor = 1315860
    DownThumbFaceColor = 6316128
    DownThumbGradColor = 3750201
    SmoothCorners = True
    ColorScheme = csDark
    Max = 255
    Frequency = 16
    TickStyle = tsAuto
    TickMarks = tmBottomRight
    Orientation = trHorizontal
    OnChange = TrackBarColorBChange
  end
  object NightModeRGBQuickEdit_ColorSample: TPanelEx
    Left = 342
    Top = 78
    Width = 93
    Height = 83
    Color1 = clWhite
    Color2 = clSilver
    Color3 = clYellow
    Color4 = clTeal
    ColorFrame = clGray
    ColorInnerFrame = clGreen
    Frames = [frLeft, frTop, frBottom]
    ParentBackground = False
    Style = vgSolid
  end
  object NightModeRGBQuickEdit_ColorSample_Current: TPanelEx
    Left = 435
    Top = 78
    Width = 93
    Height = 83
    Hint = 'Click to restore color all colors'
    Color1 = clWhite
    Color2 = clSilver
    Color3 = clYellow
    Color4 = clTeal
    ColorFrame = clGray
    ColorInnerFrame = clGreen
    Frames = [frTop, frRight, frBottom]
    ParentBackground = False
    ShowHint = True
    Style = vgSolid
    OnMouseUp = NightModeRGBQuickEdit_ColorSample_CurrentMouseUp
  end
  object LockSliders: TAdvOfficeCheckBoxEx
    Left = 196
    Top = 172
    Width = 80
    Height = 20
    Hint = 'One slider to move them all!'
    Font.Charset = ANSI_CHARSET
    Font.Color = 12574688
    Font.Height = -12
    Font.Name = 'Segoe UI'
    Font.Style = []
    ParentFont = False
    ShowHint = True
    TabOrder = 16
    Alignment = taRightJustify
    Caption = 'Lock Sliders'
    ReturnIsTab = False
    Themed = True
    CustomIconsEnabled = False
    CustomEnableIconHD = False
  end
end
